import { Router, type IRouter } from "express";
import healthRouter from "./health";
import overviewRouter from "./overview";
import demoRouter from "./demo";
import uploadsRouter from "./uploads";
import transactionsRouter from "./transactions";
import invoicesRouter from "./invoices";
import ledgerRouter from "./ledger";
import reconciliationRouter from "./reconciliation";
import risksRouter from "./risks";
import payrollRouter from "./payroll";
import gatewayRouter from "./gateway";
import reportsRouter from "./reports";
import aiRouter from "./ai";
import platformRouter from "./platform";
import monthlyCloseRouter from "./monthlyClose";
import exceptionsRouter from "./exceptions";
import actionHistoryRouter from "./actionHistory";
import trialBalanceRouter from "./trialBalance";
import journalEntriesRouter from "./journalEntries";
import gstr2bRouter from "./gstr2b";
import periodLockRouter from "./periodLock";
import excelExportRouter from "./excelExport";
import vendorAgingRouter from "./vendorAging";
import taxAuditRouter from "./taxAudit";
import practiceRouter from "./practice";
import tdsReconRouter from "./tdsRecon";

const router: IRouter = Router();

router.use(healthRouter);
router.use(overviewRouter);
router.use(demoRouter);
router.use(uploadsRouter);
router.use(transactionsRouter);
router.use(invoicesRouter);
router.use(ledgerRouter);
router.use(reconciliationRouter);
router.use(risksRouter);
router.use(payrollRouter);
router.use(gatewayRouter);
router.use(reportsRouter);
router.use(aiRouter);
router.use(platformRouter);
router.use(monthlyCloseRouter);
router.use(exceptionsRouter);
router.use(actionHistoryRouter);
router.use(trialBalanceRouter);
router.use(journalEntriesRouter);
router.use(gstr2bRouter);
router.use(periodLockRouter);
router.use(excelExportRouter);
router.use(vendorAgingRouter);
// tdsRecon must precede taxAudit: GET /tax-audit/:checkId would otherwise
// greedily match /tax-audit/tds-recon.
router.use(tdsReconRouter);
router.use(taxAuditRouter);
router.use(practiceRouter);

export default router;
